name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Usando a "Caixa Blindada" Oficial do Buildozer
      - name: Compilar APK (Via Contêiner Docker)
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # Salva o arquivo gerado
      - name: Upload do APK Final
        uses: actions/upload-artifact@v4
        with:
          name: escape-hero-apk
          # A Action já sabe o nome exato do arquivo que foi criado
          path: ${{ steps.buildozer.outputs.filename }}
